# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 81a7e9ddcd6133357d97187f54167d71bb6394df5ce9ab9c864e48b732e57842122d79a2a55f01859938a8eb095018702ee4c1e696d470f6d7296088b2b6b3e6

test:
  secret_key_base: e8134f2ffceb43b323b6f8eff73d18d33d22bd828fda3950856f9699ad291feb1c3693de2451b82173e99537de1832a7d42ca2f24e9ba0163d43a4dff7b1c95e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
